apiVersion: v1
kind: Service
metadata:
  name: hsm-server
  namespace: hsm-system
  labels:
    app.kubernetes.io/name: hsm
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hsm
    app.kubernetes.io/component: server
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
